# Puerto de la aplicación en producción
server.port=9090

# Configuración de la base de datos Oracle (PROD)
spring.datasource.url=jdbc:oracle:thin:@//prod-server:1521/PROD
spring.datasource.username=usuario_prod
spring.datasource.password=claveSeguraProd
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.main.web-application-type=servlet
# application-prod.properties
jwt.secret=${JWT_SECRET}