# Puerto de la aplicación
server.port=8080

# Configuración de la base de datos Oracle
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/EJEMPLO
spring.datasource.username=ban
spring.datasource.password=angular123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect