/*
CREATE TABLE TC_USUARIO (
    ID_USUARIO      NUMBER(10)        NOT NULL,
    USERNAME        VARCHAR2(50)      NOT NULL UNIQUE,
    PASSWORD_HASH   VARCHAR2(200)     NOT NULL,
    NOMBRE_COMPLETO VARCHAR2(150),
    EMAIL           VARCHAR2(100),
    ACTIVO          CHAR(1) DEFAULT 'S' CHECK (ACTIVO IN ('S','N')),
    FECHA_CREACION  DATE DEFAULT SYSDATE,
    CONSTRAINT PK_USUARIOS PRIMARY KEY (ID_USUARIO)
);

-- Secuencia para usuarios
CREATE SEQUENCE SEQ_USUARIOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger para asignar ID
CREATE OR REPLACE TRIGGER TRG_USUARIOS_BI
BEFORE INSERT ON TC_USUARIO
FOR EACH ROW
BEGIN
    IF :NEW.ID_USUARIO IS NULL THEN
        SELECT SEQ_USUARIOS.NEXTVAL INTO :NEW.ID_USUARIO FROM dual;
    END IF;
END;*/

/*
CREATE TABLE TC_ROL (
    ID_ROL      NUMBER(5) NOT NULL,
    NOMBRE_ROL  VARCHAR2(50) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR2(150),
    CONSTRAINT PK_ROLES PRIMARY KEY (ID_ROL)
);

-- Secuencia
CREATE SEQUENCE SEQ_ROLES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger
CREATE OR REPLACE TRIGGER TRG_ROLES_BI
BEFORE INSERT ON TC_ROL
FOR EACH ROW
BEGIN
    IF :NEW.ID_ROL IS NULL THEN
        SELECT SEQ_ROLES.NEXTVAL INTO :NEW.ID_ROL FROM dual;
    END IF;
END;
*/


CREATE TABLE TT_USUARIO_ROL (
    ID_USUARIO NUMBER(10) NOT NULL,
    ID_ROL     NUMBER(5)  NOT NULL,
    FECHA_ASIGNACION DATE DEFAULT SYSDATE,
    CONSTRAINT PK_USUARIO_ROL PRIMARY KEY (ID_USUARIO, ID_ROL),
    CONSTRAINT FK_UR_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES TC_USUARIO (ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT FK_UR_ROL FOREIGN KEY (ID_ROL)
        REFERENCES TC_ROL (ID_ROL) ON DELETE CASCADE
);
